# Server configuration
server:
  port: 27730
  
# Spring configuration
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/olibillqadb/olibillprovinceqadb;AUTO_SERVER=TRUE
    platform: h2
    data: classpath:data/provincesqa.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop